version: '3'

services:

    postgres1:
        image: postgres
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: tfstate
        ports:
        - 5432:5432
        networks:
          - frontend
        
    admin:
        image: adminer
        ports:
        - 8088:8080
        networks:
          - frontend

networks:
  frontend: