apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath: # replace with storage volume type
    path: /data